name: Base image build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: ["3.14.3", "3.15.11", "3.16.9", "3.17.10", "3.18.12", "3.19.8", "3.20.7", "3.21.4", "3.22.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract branch name
      id: extract_branch
      run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
    - name: Build and push amd64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        provenance: false
        sbom: false
        tags: |
          liskl/base:alpine-${{ matrix.alpine_version }}-amd64
          ${{ matrix.alpine_version == '3.22.1' && 'liskl/base:latest-amd64' || '' }}
        build-args: |
          RELEASE_VERSION=${{ matrix.alpine_version }}
          BRANCH=${{ env.BRANCH }}
          alpine_version=${{ matrix.alpine_version }}
          ALPINE_ARCH=x86_64
    - name: Build and push arm/v7 image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm/v7
        push: true
        provenance: false
        sbom: false
        tags: |
          liskl/base:alpine-${{ matrix.alpine_version }}-arm
          ${{ matrix.alpine_version == '3.22.1' && 'liskl/base:latest-arm' || '' }}
        build-args: |
          RELEASE_VERSION=${{ matrix.alpine_version }}
          BRANCH=${{ env.BRANCH }}
          alpine_version=${{ matrix.alpine_version }}
          ALPINE_ARCH=armhf
    - name: Create and push multi-platform manifest
      run: |
        docker manifest create liskl/base:alpine-${{ matrix.alpine_version }} \
          liskl/base:alpine-${{ matrix.alpine_version }}-amd64 \
          liskl/base:alpine-${{ matrix.alpine_version }}-arm
        docker manifest push liskl/base:alpine-${{ matrix.alpine_version }}
        
        if [ "${{ matrix.alpine_version }}" = "3.22.1" ]; then
          docker manifest create liskl/base:latest \
            liskl/base:latest-amd64 \
            liskl/base:latest-arm
          docker manifest push liskl/base:latest
        fi
